version: '3'

services:
  db: 
    image: mysql:5.7
    restart: always
    ports: 
      - "3406:3406"
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    container_name: duacoders-nestjs
    volumes:
      - ./mysql:/var/lib/mysql/data